### ISSUE TITLE
Help ( Sticker Error ) 

### ISSUE THREAD

**Issue by itshawkes127** [SlavyanDesu/BocchiBot#269] opened 2021-03-04 03:34 UTC
[ERROR] Error: ENOENT: no such file or directory, open 'C:\BocchiBot\node_modules\webp-converter\temp\1fdc5659-3ae7-4aba-9be3-2eba8fb267f4.jpg'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at base64_to_image (C:\BocchiBot\node_modules\webp-converter\src\buffer_utils.js:30:8)
    at Object.module.exports.buffer2webp (C:\BocchiBot\node_modules\webp-converter\src\buffer_utils.js:89:18)
    at Object.module.exports.buffer2webpbuffer (C:\BocchiBot\node_modules\webp-converter\src\webpconverter.js:35:23)
    at msgHandler (C:\BocchiBot\message\index.js:3139:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\BocchiBot\\node_modules\\webp-converter\\temp\\1fdc5659-3ae7-4aba-9be3-2eba8fb267f4.jpg'
}

**Comment by SlavyanDesu** [comment] 2021-03-04 19:02
Duplicate of https://github.com/SlavyanDesu/BocchiBot/issues/248.
Please head to this issue.

**Closed by SlavyanDesu** 2021-03-04 19:02 UTC
Labels: bug
