### ISSUE TITLE
/play broken 

### ISSUE THREAD

**Issue by 777days** [SlavyanDesu/BocchiBot#467] opened 2022-12-04 19:57 UTC
after the new update is /play broken 

false_49cxxxxx@c.us_BDF7DF7C1589CD049470BEABC09B7B0C

**Comment by 777days** [comment] 2022-12-04 20:00
![Screenshot_256](https://user-images.githubusercontent.com/102832954/205512638-a20af935-294f-4186-bcfe-90f1f9abe558.png)

**Comment by SlavyanDesu** [comment] 2023-01-13 19:03
Duplicate of https://github.com/SlavyanDesu/BocchiBot/issues/451

**Closed by SlavyanDesu** 2023-01-13 19:03 UTC
Labels: bug, duplicate, api related
